# Generated by Django 4.2.4 on 2023-09-03 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='address_line2',
        ),
        migrations.RemoveField(
            model_name='order',
            name='is_ordered',
        ),
    ]
